#define FONT_SIZE 11
#define LINE_SIZE 256
#define HIST_SIZE 2048
#define FPS 60
#define DEFAULTFG 15
#define VTIDEN "\033[?6c"
#define BORDERPX 5
#define FONTNAME "Hack:antialias=true:autohint=true"
#define SHELL "/bin/zsh"
